FROM mysql:8.0.33
LABEL "Project"="Vprofile"
LABEL "AUTHOR"="TEJESH"

ENV MYSQL_ROOT_PASSWORD="Your_db_pass"
ENV MYSQL_DATABASE="Your_account"

ADD db_backup.sql docker-entrypoint-initdb.d/db_backup.sql
